[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.39", features = ["derive"] }
concave_hull = { path = "../lib" }
csv = "1.3.1"
imageproc = "0.25.0"
